# Generated by Django 5.1.7 on 2025-04-20 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_itemcategory_shoppinglist_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemcategory')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shoppinglist')),
            ],
            options={
                'db_table': 'list_itemcategory',
            },
        ),
    ]
