# Generated by Django 5.1.7 on 2025-04-25 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_shared_with_sharedlist_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlist',
            name='list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.shoppinglist'),
        ),
    ]
