# Generated by Django 5.1.7 on 2025-04-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sharedlist_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedlist',
            name='url_token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
