# Generated by Django 5.1.6 on 2025-05-12 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_store_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
