# Generated by Django 5.1.6 on 2025-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shoppinglist_created_by_alter_shoppinglist_store_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('store',), name='unique_store'),
        ),
    ]
