# Generated by Django 5.1.6 on 2025-06-03 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shoppinglist_unique_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedlist',
            name='url_token',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
