# Generated by Django 5.1.6 on 2025-06-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_itemcategory_created_by_alter_sharedlist_url_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
