# Generated by Django 5.1.6 on 2025-06-13 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_shoppingitem_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list_itemcategory',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_lists', to='app.itemcategory'),
        ),
    ]
