# Generated by Django 5.1.6 on 2025-06-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_shoppingitem_is_checked_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('item_category_name', 'created_by'), name='unique_category_per_user'),
        ),
    ]
